docs/csrf.rst
Sorry missed this.
Luckily I'm have problems with this (lucky for you at least) and have reread this documentation over and over.
=> More CSRF doc updates

docs/config.rst, docs/csrf.rst
Added CSRF_WTF_CHECK_DEFAULT setting and csrf.protect() documentation.
=> Added csrf.protect() and CSRF_WTF_CHECK_DEFAULT to docs.

docs/csrf.rst
After finding the feature in the code and using it to solve a problem, I thought I would contribute by putting the feature in the docs.
=> Document csrf exempt support of Flask blueprint

flask_wtf/csrf.py, tests/test_csrf.py
In OAuth 2 there is an exploit similar to CSRF where a code exchange callback can be faked for a user. To counter that, we can pass a token during the login process, expect it to be returned upon callback, and assert against it to verify authenticity.
1. Browser is sent to `google.com/oauth?state=my-token`
2. User completes login on `google.com` and is redirected along with `state` back to our server (e.g. `localhost/oauth2callback?state=my-token`
- Reference from GitHub: https://developer.github.com/v3/oauth/#web-application-flow
- Reference from Google: https://developers.google.com/identity/protocols/OAuth2WebServer?hl=en#redirecting
The process of generating and validating a CSRF token is almost identical to how we treat/handle `state`. As a result, we would like to use the same …
=> Added support for custom token keys and making CSRF values URL safe

docs/index.rst
Fixed capitalization in few places. Will do more fixes if you accept this :)
=> Grammar fixes

docs/csrf.rst, docs/form.rst, examples/babel/app.py, examples/flaskr/flaskr.py, examples/recaptcha/app.py, flask_wtf/file.py, tests/test_i18n.py
https://github.com/pallets/flask/issues/1135#issuecomment-205427792
=> Swap from deprecated flask.ext.* to flask_*

docs/form.rst
=> Improve some awkward wording

tests/test_recaptcha.py
=> fix a misspelling

docs/config.rst
I fixed the outdated Recaptcha documention after scratching my head why `RECAPTCHA_OPTIONS` wasn't working.
=> Update config docs for Recaptcha

flask_wtf/csrf.py
Change `CsrfProtect` to `CSRFProtect`.
=> Remove deprecated name in docstring

examples/uploadr/app.py
Is only a little change, discovered executing the example to learn how file upload works
=> xrange changed to range, python3 compatible

docs/form.rst, docs/quickstart.rst
Just fixing a small grammatical  error
=> Grammar fix

setup.py
continues https://github.com/lepture/flask-wtf/pull/421
=> Add extras_require email for email-validator

tox.ini
see https://github.com/sphinx-doc/sphinx/issues/9216
This should be an intermediary fix, until a new Sphinx version gets
released.
=> fix building docs

.github/workflows/tests.yaml, README.rst, docs/_templates/useful-links.html, docs/authors.rst, docs/changelog.rst, docs/form.rst, docs/install.rst, flask_wtf/__init__.py, setup.py
Added `python_requires` metadata. Updated links and default branch name.
=> Release 0.15.1

.gitignore, CONTRIBUTING.rst, docs/contributing.rst, docs/index.rst
- Add contributing docs.
- Add `env` to `.gitignore`.
- Add an entry to the docs index page.
=> Add contributing guide

docs/index.rst
=> fix broken link

tests/test_form.py
Some routes were defined after the app first request.
=> Fixed unit tests.

src/flask_wtf/recaptcha/widgets.py
I am not sure if we should just ignore this check on this line or on the whole project.
=> Ignore flake8 B028 on the recaptcha widget

.pre-commit-config.yaml, .readthedocs.yaml, examples/recaptcha/app.py, pyproject.toml, src/flask_wtf/__init__.py, src/flask_wtf/file.py, src/flask_wtf/recaptcha/__init__.py, tests/test_file.py
Update the pre-commit configuration to use ruff and match the Flask one.
=> pre-commit configuration insipred from Flask
