pallets-eco/flask-wtf

flask_wtf/_compat.py
flask_wtf/recaptcha/validators.py
flask_wtf/recaptcha/widgets.py
tests/test_recaptcha.py

Google recently released an update to their reCaptcha service.
The old api remains working, but it would be nice to use the new api instead.
See: https://developers.google.com/recaptcha/docs/

Use reCaptcha api v2

---

examples/uploadr/app.py

The uploadr example failed with the following error message:
```bash
~/workspace/examples/uploadr$ python app.py   
Traceback (most recent call last):
File "app.py", line 2, in <module>        
from flask_wtf import Form, FieldList
ImportError: cannot import name FieldList
```
Changing the import for `FieldList` removed the error.

Fix example uploadr - wrong FieldList import

---

flask_wtf/csrf.py
tests/test_csrf.py

Somewhat significant change, I'm open to suggestions regarding the approach.
Right now, CsrfProtect._csrf_protect() does 1) check if this view should
be checked for a CSRF token, and 2) validate the actual token.
This commit abstracts 2) into a separate method so we can manually call
this method (for example on a before_request callback). This makes it
possible to do further checks before validating the CSRF (e.g. skip the
check for REST calls using OAuth).
This commit also adds a configuration parameter WTF_CSRF_CHECK_DEFAULT,
which will determine whether to check all views by default or not. It
defaults to True.

Abstract _csrf_protect() into a separate method.

---

docs/form.rst

In the current version of werkzeug, the secure_filename method must be imported from werkzeug.utils

fix example code

---

README.rst
docs/install.rst
setup.py

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

flask_wtf/form.py

As of Flask-0.11, request.json has been deprecated.
http://flask.pocoo.org/docs/0.11/changelog/
Tests pass locally:
~~~
(env)Achal’s Macbook:flask-wtf achal$ make test
.........................
----------------------------------------------------------------------
Ran 50 tests in 0.532s
OK
~~~

Use request.get_json() instead of request.json

---

flask_wtf/form.py

The first access of form.data removes the 'csrf_token' key, and
breaks on subsequent accesses.  Guard the pop() call so that a
missing value is a no-op.
Closes #208
Signed-off-by: David Aguilar <davvid@gmail.com>

form: allow form.data to be accessed multiple times

---

flask_wtf/form.py

Both PATCH and DELETE are extremely common HTTP verbs and occur when submitting
a form, so let's include them.

Add PATCH/DELETE support to validate_on_submit

---

docs/api.rst
examples/babel/app.py
examples/flaskr/flaskr.py
examples/recaptcha/app.py
examples/uploadr/app.py
flask_wtf/__init__.py
flask_wtf/_compat.py
flask_wtf/form.py
tests/base.py
tests/test_form.py
tests/test_recaptcha.py
tests/test_uploads.py

Show deprecation warning when using `Form`.
closes #249

Rename Form to FlaskForm

---

flask_wtf/csrf.py

We have noticed an inconsistent behavior for when a 404 is being exempted/not exempted from a CSRF check.
Initially in our repo, we had no `@csrf.exempt` calls and so a test like the following would receive a CSRF error (not a 404):
```python
@app.route('/foo', methods=('GET', 'POST'))
def my_handler():
return 'ok'
self.app.post('/not-an-endpoint')
```
However, after we add an `@csrf.exempt` to an existing endpoint, we noticed that we would instead yield a 404 at the endpoint in our tests:
```python
@csrf.exempt
@app.route('/foo', methods=('GET', 'POST'))
def my_handler():
return 'ok'
self.app.post('/not-an-endpoint')
```
This inconsistent behavior is undesirable as some people might be writing integration tests to verify CSRF works.
To remedy that, we have decided to exempt all 404 …

Repaired 404 exemption inconsistency

---

docs/api.rst
docs/changelog.rst
docs/csrf.rst
flask_wtf/_compat.py
flask_wtf/csrf.py
flask_wtf/form.py
tests/base.py
tests/templates/csrf_macro.html
tests/test_csrf.py
tests/test_validation.py

- Use itsdangerous to sign tokens and check expiration, instead of rolling our own.
- All tokens are url safe, essentially reverting #206.  There is no longer a `url_safe` parameter. cc @twolfson 
- All tokens store a timstamp, which is checked in `validate_csrf`.  There is no longer a `time_limit` parameter to `generate_csrf`.
- Fix anti-pattern of storing `app` on extension, use `current_app` when needed.
- Add the `DELETE` method as protected by default.
- Generate the same signed token over the lifetime of a request. Exposed as `request.csrf_token`. (#227)
- `@csrf.error_handler` is deprecated in favor of the standard Flask error system `@app.errorhandler(CSRFError)`.
- decorator is "fixed" so that it handles both raising an exception or returning a response.  A returned response is …

CSRF cleanup and fixes

---

docs/api.rst
docs/changelog.rst
docs/config.rst
docs/csrf.rst
flask_wtf/__init__.py
flask_wtf/csrf.py
flask_wtf/form.py
tests/base.py
tests/test_csrf.py
tests/test_deprecated.py
tests/test_form.py
tests/test_i18n.py
tests/test_recaptcha.py
tests/test_uploads.py
tests/test_validation.py

- Use `Form.Meta` instead of deprecated `SecureForm` for CSRF (and
everything else). (#216)
- `csrf_enabled` parameter is still recognized but deprecated.
- All other attributes and methods from `SecureForm` are removed. **This breaks anything using them.** These were really just side effects of `SecureForm`, so I didn't try to deprecate everything as no one should really have been using those parts in the first place.
- Provide `WTF_CSRF_FIELD_NAME` to configure the name of the CSRF token.
- `validate_csrf` raises `wtforms.ValidationError` with specific messages
instead of returning `True` or `False`. **This breaks anything that was
calling the method directly.**
- CSRF errors are logged as well as raised. (#239)
- I tried, but could not come up with a sane way to deprecate the old …

Switch to Form.Meta from SecureForm, improve CSRF errors

---

docs/api.rst
docs/changelog.rst
docs/conf.py
docs/form.rst
flask_wtf/file.py

Move the remainder of `has_file` into the two decorators, since it's only an instance check now. Use the decorators with WTForms' normal `FileField`.

Deprecate FileField

---

docs/changelog.rst
flask_wtf/file.py

closes #276
- `FileField` is no longer deprecated. The data is checked during
processing and only set if it's a valid file.
- `has_file` *is* deprecated; it's now equivalent to
`bool(field.data).
- `FileRequired` and `FileAllowed` work with both the Flask-WTF and
WTForms `FileField` classes.
- The `Optional` validator now works with `FileField`.

file validators correctly identify empty data

---

docs/form.rst
flask_wtf/form.py
tests/test_form.py

I had hard times understanding the deprecation of `csrf_enabled`. The only way I managed to do it was by reading *form.py*. 
Let's make the doc and deprecation message better :-)

Fix forms & csrf_enabled deprecation doc

---

setup.py

Since flask-wtf directly uses the itsdangerous dependency in [csrf.py](https://github.com/lepture/flask-wtf/blob/master/flask_wtf/csrf.py) it should be included in setup.py.

Include itsdangerous dependency in install_requires

---

docs/config.rst
flask_wtf/form.py
tests/test_form.py

With this PR, people can change the built-in error message's default language.
Address #303 and #300.

Add support to change message language

---

docs/quickstart.rst

Clearly a typo, would cause `405 Method Not Allowed`.
Please let me know if you need an issue raised for this, thanks.

Quickstart: methods param for /submit route should be [], not ()

---

docs/conf.py

Otherwise recent Sphinx versions display the following warning:
```
RemovedInSphinx17Warning: html_use_smartypants option is deprecated
```
See http://www.sphinx-doc.org/en/1.6.7/config.html#confval-smartquotes

Fix Sphinx deprecation warning, requires Sphinx 1.6.6

---

flask_wtf/recaptcha/validators.py
flask_wtf/recaptcha/widgets.py

Addresses Issue #377 
`werkzeug==0.16.0` started giving the following deprecation warning:
The import 'werkzeug.url_encode' is deprecated and will be removed in Werkzeug 1.0.
Use 'from werkzeug.urls import url_encode' instead.

Update imports for werkzeug==0.16.0

---

flask_wtf/_compat.py
flask_wtf/file.py

Iterable should be imported from collections.abc instead of from
collections.
modified:   flask_wtf/file.py

Fix deprecation warning

---

.travis.yml

cf. https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove obsolete `sudo` keyword

---

flask_wtf/csrf.py

There is a small typo in flask_wtf/csrf.py.
Should read `comparison` rather than `comparision`.

docs: Fix simple typo, comparision -> comparison

---

docs/config.rst

There are many issues ( #333, #331 ) related to this usage, so maybe it's better to address it in the documentation.

Clarify how to use WTForms's built-in messages

---

docs/quickstart.rst

I had to look at http://flask.pocoo.org/docs/0.12/patterns/wtforms/#forms-in-templates to see how to do this, and thought it would make a good addition to the Flask-WTF docs themselves.

Add to docs with example of validation errors in templates

---

flask_wtf/form.py

Hi,
I recently updated a project to use Flask 2.0 which came with Jinja 3.0 as a dependency.
After doing that upgrade I started to get this warning from Flask-WTF:
```
python3.9/site-packages/flask_wtf/form.py:133: DeprecationWarning: 'jinja2.Markup' is deprecated
and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.
return Markup(
```
This PR takes that advice and imports `Markup` from `markupsafe` instead of `jinja2`.

Fix Flask 2.0+ deprecation warning related to using jinja2.Markup, now it uses markupsafe.Markup

---

docs/quickstart.rst

This PR replaces `form.name` with `form.name.errors` in `docs/quickstart.rst` as suggested by me in #451.
- fixes #451

docs: quickstart: iterate errors, not object itself

---

docs/changes.rst
docs/config.rst
src/flask_wtf/recaptcha/validators.py
src/flask_wtf/recaptcha/widgets.py
tests/test_recaptcha.py

Hi,
This merge request would add support for more CAPTCHA services, e.g. hCaptcha, a privacy focused non-Google alternative to reCAPTCHA.
If desired I could also add an additional  hCaptcha entry to the `examples/`.
Cheers!

Add support for alternative captcha services

---

MANIFEST.in

Hi,
This fixes the following error:
```
Flask-WTF-1.0.0/docs/contributing.rst:1: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'CONTRIBUTING.rst'.
```
Since this affects the doc build, I didn't include the checklist.

Include CONTRIBUTING.rst in source distributions

---

src/flask_wtf/form.py

Add the `extra_validators` parameter to the `validate_on_submit()` method and pass it to WTForms's `Form.validate()` method.

Add extra_validators parameter to validate_on_submit

---

examples/babel/app.py

`examples/babel/app.py` still imports `TextField` from `wtforms` which has been removed. This PR changes it to `StringField`.
Checklist:

Fix Babel Example

---

docs/changes.rst
src/flask_wtf/i18n.py
tests/test_i18n.py
tox.ini

The project has been [discontinuited since November 22](https://github.com/mrjoes/flask-babelex).

Stop supporting Flask-Babelex

---

src/flask_wtf/recaptcha/widgets.py

Set JSONEncoder to json._default

---

src/flask_wtf/form.py

Fix the validate of form should pass extra_validators

---

examples/babel/app.py
tests/test_i18n.py

Flask-Babel 3.0.0 has been released yesterday. The [CHANGELOG](https://github.com/python-babel/flask-babel/blob/master/CHANGELOG) indicates that:
> - Babel.locale_selector and Babel.timezone_selector no longer exist. They must be provided
either when the Babel() object is created or when init_app() is called. This is to support
having a single Babel object for multiple Flask apps ([#107](https://github.com/python-babel/flask-babel/issues/107)) as well as to simplify settings
and multi-threaded state.
Those decorators were not used except in unit tests and examples. This PR fixes the unit tests and the CI with flask-babel 3.

Fixed unit tests for Flask-Babel 3

---

docs/changes.rst
src/flask_wtf/recaptcha/validators.py
src/flask_wtf/recaptcha/widgets.py
tests/test_recaptcha.py

This fixes all deprecation warnings (`url_encode` and importing `Markup`) introduced with Flask 2.3 and continues #562.
I added a changelog entry as requested by the PR template, I hope version `1.1.2` is fine as the new unreleased version?
- fixes #561
- supersedes #562
Checklist:

Fix Flask 2.3 deprecations

---

tox.ini

flask-uploads had no release since 2016, and with the release of werkzeug 1.0 some imports were broken. They were fixed but never released. https://github.com/maxcountryman/flask-uploads/pull/28. Apparently this is not going to change until someone implements tag based release for the project. https://github.com/maxcountryman/flask-uploads/issues/39
flask-reuploaded is a drop-in replacement for flask-uploads, and is actively maintained
https://github.com/jugmac00/flask-reuploaded
This only concerns tests, some of which were skipped due to the buggy imports.

chore: test against flask-reuploaded instead of flask-uploads

---

docs/changes.rst
src/flask_wtf/csrf.py
tests/test_csrf_extension.py

This is done by storing the blueprint objects instead of their names.
fixes #486

nested blueprints can be CSRF exempted

---

docs/changes.rst
docs/form.rst
src/flask_wtf/file.py
tests/test_file.py

Continue #338
- Add the `MultipleFileField` field.
- Update `FileRequired`, `FileAllowed`, and `FileSize` to make them work with multiple files.
- Add tests for using Length with the files field.
fixes #337
fixes #393
Checklist:

Add `MultipleFileField` and support validating multiple files

---

docs/changes.rst
src/flask_wtf/file.py

When I was playing with the last flask-wtf I noticed that the file validators were editing the `field.data` since #556, leading to incompatibilities: on simple `FileField` my code was expecting a simple `FileStorage` and not a list of `FileStorage`. However the `if not isinstance(field.data, list): field.data = [field.data]` lines was setting a list even for simple `FileField`
@greyli what do you think?

 fix: file validators were editing the file fields content
